# Generated by Django 4.2.28 on 2026-02-21 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(default='')),
                ('value_type', models.CharField(choices=[('STRING', 'Text'), ('INTEGER', 'Whole Number'), ('FLOAT', 'Decimal Number'), ('BOOLEAN', 'Yes / No'), ('JSON', 'Advanced (JSON)')], default='STRING', max_length=10)),
                ('category', models.CharField(choices=[('CIRCULATION', 'Circulation'), ('ENGAGEMENT', 'Engagement'), ('SECURITY', 'Security'), ('GENERAL', 'General'), ('NOTIFICATIONS', 'Notifications')], default='GENERAL', max_length=20)),
                ('label', models.CharField(help_text='Human-readable name shown in admin UI', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Explanation shown to admin')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Mask value in UI')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'common_system_settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
