# Generated by Django 6.0.2 on 2026-02-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('CIRCULATION', 'Circulation'), ('ENGAGEMENT', 'Engagement'), ('SECURITY', 'Security'), ('GENERAL', 'General'), ('NOTIFICATIONS', 'Notifications'), ('EMAIL', 'Email / SMTP')], default='GENERAL', max_length=20),
        ),
    ]
