# Generated by Django 4.2.28 on 2026-02-21 20:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(help_text='Unique tag e.g. NOVA-ASSET-0001', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & In Use'), ('IN_STORAGE', 'In Storage'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('DISPOSED', 'Disposed / Written Off'), ('ON_ORDER', 'On Order')], default='ACTIVE', max_length=20)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=20)),
                ('floor_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('room', models.CharField(blank=True, default='', max_length=100)),
                ('location_notes', models.TextField(blank=True, default='')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5, help_text='Expected useful life in years')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('model_number', models.CharField(blank=True, default='', max_length=100)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_interval_days', models.PositiveIntegerField(blank=True, help_text='Days between scheduled maintenance', null=True)),
                ('image_url', models.URLField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Scheduled / Preventive'), ('CORRECTIVE', 'Corrective / Repair'), ('INSPECTION', 'Inspection'), ('UPGRADE', 'Upgrade / Enhancement')], max_length=20)),
                ('description', models.TextField()),
                ('performed_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('condition_after', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='asset_management.asset')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_maintenance_log',
                'ordering': ['-performed_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('SOLD', 'Sold'), ('DONATED', 'Donated'), ('RECYCLED', 'Recycled'), ('SCRAPPED', 'Scrapped'), ('TRANSFERRED', 'Transferred')], max_length=20)),
                ('disposed_date', models.DateField()),
                ('disposal_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='asset_management.asset')),
            ],
            options={
                'db_table': 'asset_disposal',
                'ordering': ['-disposed_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='asset_management.assetcategory')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='asset_management.assetcategory'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='asset_asset_status_882797_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category'], name='asset_asset_categor_c96578_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_tag'], name='asset_asset_asset_t_cec28d_idx'),
        ),
    ]
