# Generated by Django 6.0.2 on 2026-02-21 19:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(choices=[('READING', 'Reading'), ('BORROWING', 'Borrowing'), ('SOCIAL', 'Social'), ('STREAK', 'Streak'), ('MILESTONE', 'Milestone'), ('SPECIAL', 'Special')], db_index=True, max_length=20)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20)),
                ('kp_reward', models.PositiveIntegerField(default=0)),
                ('criteria', models.JSONField(default=dict, help_text='{"type": "books_read", "threshold": 10}')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'engagement_achievement',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('kp_earned', models.PositiveIntegerField(default=0)),
                ('books_borrowed', models.PositiveSmallIntegerField(default=0)),
                ('books_returned', models.PositiveSmallIntegerField(default=0)),
                ('reading_minutes', models.PositiveIntegerField(default=0)),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('reviews_written', models.PositiveSmallIntegerField(default=0)),
                ('sessions_completed', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'engagement_daily_activity',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kp_awarded', models.PositiveIntegerField(default=0)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'engagement_user_achievement',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('total_kp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('level_title', models.CharField(default='Novice Reader', max_length=50)),
                ('explorer_kp', models.PositiveIntegerField(default=0, help_text='Borrowing/browsing')),
                ('scholar_kp', models.PositiveIntegerField(default=0, help_text='Completion/reviews')),
                ('connector_kp', models.PositiveIntegerField(default=0, help_text='Social/sharing')),
                ('achiever_kp', models.PositiveIntegerField(default=0, help_text='Achievements/milestones')),
                ('dedicated_kp', models.PositiveIntegerField(default=0, help_text='Streaks/consistency')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('kp_earned_today', models.PositiveIntegerField(default=0)),
                ('kp_today_date', models.DateField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'engagement_user_engagement',
                'ordering': ['-total_kp'],
            },
        ),
    ]
