# Generated by Django 6.0.2 on 2026-02-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='engagement.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['user', '-date'], name='idx_daily_user_date'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', '-earned_at'], name='idx_uachv_user_time'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['-total_kp'], name='idx_eng_total_kp'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['level'], name='idx_eng_level'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['rank'], name='idx_eng_rank'),
        ),
    ]
