# Generated by Django 6.0.2 on 2026-02-21 19:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('OVERDUE', 'Overdue Return'), ('LOST', 'Lost Book'), ('DAMAGE', 'Book Damage')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('PARTIALLY_PAID', 'Partially Paid')], db_index=True, default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('description', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circulation_fine',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready for Pickup'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'circulation_reservation',
                'ordering': ['queue_position', 'reserved_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationBan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('reason', models.TextField(default='Excessive no-show reservations.')),
                ('no_show_count', models.PositiveIntegerField(default=0, help_text='Number of no-show reservations that triggered this ban.')),
                ('banned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='When the ban lifts automatically.')),
                ('lifted_at', models.DateTimeField(blank=True, help_text='If manually lifted early by staff.', null=True)),
            ],
            options={
                'db_table': 'circulation_reservation_ban',
                'ordering': ['-banned_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost')], db_index=True, default='ACTIVE', max_length=20)),
                ('borrowed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.PositiveSmallIntegerField(default=0)),
                ('max_renewals', models.PositiveSmallIntegerField(default=2)),
                ('condition_at_borrow', models.CharField(blank=True, default='', max_length=20)),
                ('condition_at_return', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='catalog.bookcopy')),
            ],
            options={
                'db_table': 'circulation_borrow_record',
                'ordering': ['-borrowed_at'],
            },
        ),
    ]
