# Generated by Django 6.0.2 on 2026-02-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('circulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_borrows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='returned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='borrow_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='circulation.borrowrecord'),
        ),
        migrations.AddField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_fines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='assigned_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='catalog.bookcopy'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='reservation',
            field=models.OneToOneField(blank=True, help_text='The reservation that was fulfilled to create this borrow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_record', to='circulation.reservation'),
        ),
        migrations.AddField(
            model_name='reservationban',
            name='lifted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['user', 'status'], name='idx_fine_user_status'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['status', '-issued_at'], name='idx_fine_status_time'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='idx_resv_user_status'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['book', 'status'], name='idx_resv_book_status'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'reserved_at'], name='idx_resv_status_time'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['expires_at'], name='idx_resv_expires'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'READY'])), fields=('user', 'book'), name='uniq_active_reservation'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['user', 'status'], name='idx_borrow_user_status'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['book_copy', 'status'], name='idx_borrow_copy_status'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['status', 'due_date'], name='idx_borrow_status_due'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['-borrowed_at'], name='idx_borrow_time'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['due_date'], name='idx_borrow_due'),
        ),
        migrations.AddIndex(
            model_name='reservationban',
            index=models.Index(fields=['user', 'expires_at'], name='idx_ban_user_exp'),
        ),
    ]
