# Generated by Django 6.0.2 on 2026-02-21 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('FAILED_LOGIN', 'Failed Login'), ('BRUTE_FORCE', 'Brute Force Detected'), ('TOKEN_REUSE', 'Refresh Token Reuse'), ('RATE_LIMIT', 'Rate Limit Exceeded'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation Attempt'), ('DATA_EXPORT', 'Bulk Data Export'), ('ACCOUNT_LOCKED', 'Account Locked'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'governance_security_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, help_text='User who performed the action.', null=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('BORROW', 'Borrow'), ('RETURN', 'Return'), ('RENEW', 'Renew'), ('RESERVE', 'Reserve'), ('VERIFY', 'Verify'), ('KP_AWARD', 'KP Award'), ('KP_DEDUCT', 'KP Deduct'), ('FINE_ISSUE', 'Fine Issue'), ('FINE_PAY', 'Fine Pay'), ('SESSION_START', 'Session Start'), ('SESSION_END', 'Session End'), ('ROLE_CHANGE', 'Role Change'), ('PASSWORD_CHANGE', 'Password Change'), ('SYSTEM', 'System')], db_index=True, max_length=30)),
                ('resource_type', models.CharField(db_index=True, help_text='e.g. User, Book, BorrowRecord', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', help_text='ID of the affected resource.', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'governance_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='idx_audit_action_time'), models.Index(fields=['actor_id', 'created_at'], name='idx_audit_actor_time'), models.Index(fields=['resource_type', 'resource_id'], name='idx_audit_resource'), models.Index(fields=['-created_at'], name='idx_audit_created')],
            },
        ),
        migrations.CreateModel(
            name='KPLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('AWARD', 'Award'), ('DEDUCT', 'Deduct'), ('BONUS', 'Bonus'), ('PENALTY', 'Penalty'), ('EXPIRE', 'Expire'), ('ADMIN_ADJUST', 'Admin Adjustment')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for award, negative for deduction.')),
                ('balance_after', models.IntegerField(help_text='KP balance after this transaction.')),
                ('source_type', models.CharField(blank=True, default='', help_text='e.g. BORROW_RETURN, READING_SESSION, LOGIN_STREAK', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=255)),
                ('dimension', models.CharField(blank=True, default='', help_text='KP dimension: EXPLORER, SCHOLAR, etc.', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'KP Ledger Entry',
                'verbose_name_plural': 'KP Ledger Entries',
                'db_table': 'governance_kp_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='idx_kp_user_time'), models.Index(fields=['action', '-created_at'], name='idx_kp_action_time'), models.Index(fields=['source_type'], name='idx_kp_source'), models.Index(fields=['dimension'], name='idx_kp_dimension')],
            },
        ),
    ]
