# Generated by Django 4.2.28 on 2026-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('BORROW', 'Borrow'), ('RETURN', 'Return'), ('RENEW', 'Renew'), ('RESERVE', 'Reserve'), ('VERIFY', 'Verify'), ('KP_AWARD', 'KP Award'), ('KP_DEDUCT', 'KP Deduct'), ('FINE_ISSUE', 'Fine Issue'), ('FINE_PAY', 'Fine Pay'), ('SESSION_START', 'Session Start'), ('SESSION_END', 'Session End'), ('ROLE_CHANGE', 'Role Change'), ('PASSWORD_CHANGE', 'Password Change'), ('CONFIRM_PICKUP', 'Confirm Pickup'), ('REGISTER_WITH_NIC', 'Register with NIC'), ('UPDATE_ROLE_CONFIG', 'Update Role Config'), ('CREATE_ROLE_CONFIG', 'Create Role Config'), ('DELETE_ROLE_CONFIG', 'Delete Role Config'), ('SYSTEM', 'System')], db_index=True, max_length=30),
        ),
    ]
