# Generated by Django 6.0.2 on 2026-02-21 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('EMBEDDING', 'Embedding Model'), ('RECOMMENDATION', 'Recommendation Model'), ('OCR', 'OCR Pipeline'), ('FACE', 'Face Recognition')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('config', models.JSONField(default=dict, help_text='Model hyper-parameters and config.')),
                ('metrics', models.JSONField(default=dict, help_text='Evaluation metrics (accuracy, precision, etc.).')),
                ('is_active', models.BooleanField(default=False, help_text='Only one version per model_type should be active.')),
                ('artifact_path', models.CharField(blank=True, default='', help_text='Path to the serialised model artifact.', max_length=500)),
            ],
            options={
                'db_table': 'intelligence_ai_model_version',
                'ordering': ['-created_at'],
                'unique_together': {('model_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('OLLAMA', 'Ollama (Local)'), ('GEMINI', 'Google Gemini'), ('OPENAI', 'OpenAI'), ('LOCAL_TRANSFORMERS', 'Local Transformers')], max_length=30)),
                ('capability', models.CharField(choices=[('CHAT', 'Chat / Text Generation'), ('EMBEDDING', 'Embedding'), ('SUMMARIZATION', 'Summarization'), ('CLASSIFICATION', 'Classification')], max_length=30)),
                ('display_name', models.CharField(help_text='Human-friendly label, e.g. "Ollama llama3.1 8B"', max_length=200)),
                ('model_name', models.CharField(help_text='Model identifier: llama3.1, gemini-pro, gpt-4o-mini, etc.', max_length=200)),
                ('api_base_url', models.URLField(blank=True, default='', help_text='Base URL for the API (e.g. http://localhost:11434 for Ollama).', max_length=500)),
                ('api_key', models.CharField(blank=True, default='', help_text='API key (encrypted at rest). Leave blank for local providers.', max_length=500)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific settings (temperature, top_p, etc.).')),
                ('is_active', models.BooleanField(default=False, help_text='Only one config per capability should be active.')),
                ('is_healthy', models.BooleanField(default=False, help_text='Last health-check result.')),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'intelligence_ai_provider_config',
                'ordering': ['capability', '-is_active', '-created_at'],
                'indexes': [models.Index(fields=['capability', 'is_active'], name='intelligenc_capabil_dfb015_idx'), models.Index(fields=['provider'], name='intelligenc_provide_b099da_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('preferred_categories', models.JSONField(blank=True, default=list, help_text='List of category IDs the user explicitly prefers.')),
                ('preferred_authors', models.JSONField(blank=True, default=list, help_text='List of author IDs the user explicitly prefers.')),
                ('preferred_languages', models.JSONField(blank=True, default=list)),
                ('disliked_categories', models.JSONField(blank=True, default=list)),
                ('reading_speed', models.CharField(blank=True, default='', help_text='slow / average / fast — inferred from sessions.', max_length=20)),
                ('preference_vector', models.JSONField(blank=True, help_text='Embedding vector derived from reading history.', null=True)),
                ('last_computed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_user_preference',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('strategy', models.CharField(choices=[('COLLABORATIVE', 'Collaborative Filtering'), ('CONTENT_BASED', 'Content-Based'), ('HYBRID', 'Hybrid'), ('TRENDING', 'Trending / Popular'), ('SIMILAR_USERS', 'Similar Users'), ('BECAUSE_YOU_READ', 'Because You Read')], default='HYBRID', max_length=30)),
                ('score', models.FloatField(help_text='Relevance score 0.0–1.0')),
                ('explanation', models.TextField(blank=True, default='', help_text='Human-readable reason for the recommendation.')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalog.book')),
                ('seed_book', models.ForeignKey(blank=True, help_text='Book that triggered "because you read" recs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_recommendation',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['user', '-score'], name='intelligenc_user_id_17c45b_idx'), models.Index(fields=['user', 'strategy'], name='intelligenc_user_id_8964b5_idx'), models.Index(fields=['book'], name='intelligenc_book_id_0e2404_idx'), models.Index(fields=['-created_at'], name='intelligenc_created_2e37a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('query_text', models.CharField(max_length=500)),
                ('filters_applied', models.JSONField(blank=True, default=dict, help_text='Filters active during the search.')),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_result_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='Groups searches within the same user session.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_search_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['query_text'], name='intelligenc_query_t_dc73bc_idx'), models.Index(fields=['-timestamp'], name='intelligenc_timesta_0687f9_idx'), models.Index(fields=['user', '-timestamp'], name='intelligenc_user_id_eb3774_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrendingBook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ALL_TIME', 'All Time')], max_length=10)),
                ('rank', models.PositiveIntegerField()),
                ('borrow_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_entries', to='catalog.book')),
            ],
            options={
                'db_table': 'intelligence_trending_book',
                'ordering': ['period', 'rank'],
                'indexes': [models.Index(fields=['period', 'rank'], name='intelligenc_period_6228f8_idx')],
                'unique_together': {('book', 'period')},
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('OVERDUE_WARNING', 'Predicted Overdue Warning'), ('RECOMMENDATION', 'New Recommendation'), ('ACHIEVEMENT', 'Achievement Unlocked'), ('STREAK_REMINDER', 'Streak At Risk'), ('NEW_ARRIVAL', 'New Book Arrival'), ('RESERVATION_READY', 'Reservation Ready'), ('RE_ENGAGEMENT', 'Re-engagement Nudge'), ('KP_MILESTONE', 'KP Level Milestone'), ('DUE_DATE_REMINDER', 'Due Date Reminder')], max_length=30)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], default='IN_APP', max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='If set, delivery is deferred until this time.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='intelligenc_user_id_b7302e_idx'), models.Index(fields=['user', 'is_read'], name='intelligenc_user_id_5ffcdb_idx'), models.Index(fields=['notification_type'], name='intelligenc_notific_186d3e_idx'), models.Index(fields=['scheduled_for'], name='intelligenc_schedul_a3a096_idx')],
            },
        ),
    ]
