# Generated by Django 6.0.2 on 2026-02-21 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='strategy',
            field=models.CharField(choices=[('COLLABORATIVE', 'Collaborative Filtering'), ('CONTENT_BASED', 'Content-Based'), ('HYBRID', 'Hybrid'), ('TRENDING', 'Trending / Popular'), ('SIMILAR_USERS', 'Similar Users'), ('BECAUSE_YOU_READ', 'Because You Read'), ('BROWSE_BASED', 'Based on Browsing History')], default='HYBRID', max_length=30),
        ),
        migrations.CreateModel(
            name='BookView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Approximate time on the detail page (updated on leave).')),
                ('source', models.CharField(blank=True, default='catalog', help_text='Where the view originated: catalog, search, recommendation, trending.', max_length=30)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_book_view',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='intelligenc_user_id_f0103d_idx'), models.Index(fields=['book', '-viewed_at'], name='intelligenc_book_id_1102cb_idx'), models.Index(fields=['-viewed_at'], name='intelligenc_viewed__d80dd3_idx')],
            },
        ),
    ]
