# Generated by Django 6.0.2 on 2026-02-21 19:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.JSONField(help_text='{"page": N, "offset": N} or {"seconds": N}')),
                ('note', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='yellow', max_length=20)),
            ],
            options={
                'db_table': 'digital_content_bookmark',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this record was soft-deleted. NULL means active.', null=True)),
                ('asset_type', models.CharField(choices=[('EBOOK_EPUB', 'eBook (EPUB)'), ('EBOOK_PDF', 'eBook (PDF)'), ('AUDIOBOOK', 'Audiobook')], db_index=True, max_length=20)),
                ('file_path', models.CharField(help_text='Relative path in object storage.', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash for integrity.', max_length=128)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Total duration for audiobooks.', null=True)),
                ('narrator', models.CharField(blank=True, default='', max_length=200)),
                ('total_pages', models.PositiveIntegerField(blank=True, help_text='Total page count for eBooks.', null=True)),
                ('is_drm_protected', models.BooleanField(default=False)),
                ('upload_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'digital_content_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('position_start', models.JSONField(help_text='{"page": N, "offset": N}')),
                ('position_end', models.JSONField(help_text='{"page": N, "offset": N}')),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'digital_content_highlight',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, help_text='0.00 to 100.00', max_digits=5)),
                ('last_position', models.JSONField(blank=True, help_text='Bookmark position: {"page": N} or {"seconds": N}.', null=True)),
                ('kp_awarded', models.PositiveIntegerField(default=0)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'digital_content_reading_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'digital_content_user_library',
                'ordering': ['-last_accessed_at'],
            },
        ),
    ]
