# Generated by Django 6.0.2 on 2026-02-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('digital_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='digital_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='digital_content.digitalasset'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='digital_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='digital_content.digitalasset'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='digital_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='digital_content.digitalasset'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='digital_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='digital_content.digitalasset'),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_library', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='digitalasset',
            index=models.Index(fields=['book', 'asset_type'], name='idx_asset_book_type'),
        ),
        migrations.AddIndex(
            model_name='digitalasset',
            index=models.Index(fields=['asset_type'], name='idx_asset_type'),
        ),
        migrations.AlterUniqueTogether(
            name='digitalasset',
            unique_together={('book', 'asset_type')},
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'digital_asset'], name='idx_bookmark_user_asset'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['user', 'digital_asset'], name='idx_highlight_user_asset'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['user', '-started_at'], name='idx_session_user_time'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['digital_asset', 'user'], name='idx_session_asset_user'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['status'], name='idx_session_status'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['session_type'], name='idx_session_type'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['user', '-last_accessed_at'], name='idx_ulib_user_access'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['user', 'is_favorite'], name='idx_ulib_user_fav'),
        ),
        migrations.AlterUniqueTogether(
            name='userlibrary',
            unique_together={('user', 'digital_asset')},
        ),
    ]
