# Generated by Django 4.2.28 on 2026-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='last_position',
            field=models.JSONField(blank=True, help_text='Last reading/listening position: {"page": N} or {"time": N}.', null=True),
        ),
    ]
