# Generated by Django 6.0.2 on 2026-02-21 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this record was soft-deleted. NULL means active.', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic concurrency control.')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('isbn_10', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('isbn_13', models.CharField(db_index=True, max_length=13, unique=True)),
                ('publisher', models.CharField(blank=True, default='', max_length=300)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, default='', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('table_of_contents', models.TextField(blank=True, default='')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('dewey_decimal', models.CharField(blank=True, default='', max_length=20)),
                ('lcc_number', models.CharField(blank=True, default='', max_length=50)),
                ('total_copies', models.PositiveIntegerField(default=0)),
                ('available_copies', models.PositiveIntegerField(default=0)),
                ('total_borrows', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('embedding_vector', models.JSONField(blank=True, help_text='Semantic embedding for AI recommendations.', null=True)),
            ],
            options={
                'db_table': 'catalog_book',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this record was soft-deleted. NULL means active.', null=True)),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('WORN', 'Worn'), ('DAMAGED', 'Damaged')], default='NEW', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Under Maintenance'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20)),
                ('floor_number', models.PositiveSmallIntegerField(blank=True, help_text='Floor number where this copy is shelved.', null=True)),
                ('shelf_number', models.CharField(blank=True, default='', help_text='Shelf identifier, e.g. A3, B12.', max_length=50)),
                ('shelf_location', models.CharField(blank=True, default='', help_text='Legacy free-text location field.', max_length=100)),
                ('branch', models.CharField(blank=True, default='main', help_text='Library branch identifier.', max_length=100)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Book Copies',
                'db_table': 'catalog_book_copy',
                'ordering': ['barcode'],
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating 1-5')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_book_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon identifier for the UI.', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'catalog_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('biography', models.TextField(blank=True, default='')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'catalog_author',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='idx_author_name')],
            },
        ),
    ]
