# Generated by Django 6.0.2 on 2026-02-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='catalog.author'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='catalog.category'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['barcode'], name='idx_copy_barcode'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['book', 'status'], name='idx_copy_book_status'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['status'], name='idx_copy_status'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['branch'], name='idx_copy_branch'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', '-created_at'], name='idx_review_book_time'),
        ),
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together={('book', 'user')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='idx_book_title'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn_13'], name='idx_book_isbn13'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn_10'], name='idx_book_isbn10'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publisher'], name='idx_book_publisher'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language'], name='idx_book_language'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-total_borrows'], name='idx_book_popularity'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-average_rating'], name='idx_book_rating'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='idx_book_created'),
        ),
    ]
