# Generated by Django 6.0.2 on 2026-02-21 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this record was soft-deleted. NULL means active.', null=True)),
                ('email', models.EmailField(db_index=True, help_text='Primary email address used for authentication.', max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('LIBRARIAN', 'Librarian'), ('ASSISTANT', 'Library Assistant'), ('USER', 'User')], db_index=True, default='USER', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the user can log in. Set to True after verification.')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user can access the Django admin.')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has passed identity verification.')),
                ('verification_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('MANUAL_REVIEW', 'MANUAL_REVIEW')], default='PENDING', max_length=20)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('institution_id', models.CharField(blank=True, default='', help_text='Student/staff ID number.', max_length=50)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'identity_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the refresh token value.', max_length=255, unique=True)),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('is_revoked', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_to', to='identity.refreshtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'db_table': 'identity_refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('id_document_path', models.CharField(max_length=500)),
                ('selfie_path', models.CharField(max_length=500)),
                ('extracted_name', models.CharField(blank=True, default='', max_length=200)),
                ('extracted_id_number', models.CharField(blank=True, default='', max_length=100)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('face_match_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('MANUAL_REVIEW', 'MANUAL_REVIEW')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'db_table': 'identity_verification_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='idx_user_role_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='idx_user_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['token_hash'], name='idx_refresh_token_hash'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'is_revoked'], name='idx_refresh_user_active'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['user', 'status'], name='idx_verification_user_status'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['status', 'created_at'], name='idx_verification_pending'),
        ),
    ]
