# Generated by Django 4.2.28 on 2026-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nic_number',
            field=models.CharField(blank=True, default='', help_text='National Identity Card number.', max_length=20),
        ),
    ]
