# Generated by Django 4.2.28 on 2026-02-22 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_nic_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('role_key', models.CharField(db_index=True, help_text='Unique machine-readable key for this role e.g. LIBRARIAN, CUSTOM_ROLE.', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name e.g. "Librarian", "Senior Assistant".', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('permissions', models.JSONField(default=dict, help_text='JSON dict mapping module keys to lists of allowed actions.')),
                ('is_system', models.BooleanField(default=False, help_text='System roles (SUPER_ADMIN, LIBRARIAN, etc.) cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Role Configuration',
                'verbose_name_plural': 'Role Configurations',
                'db_table': 'identity_role_configs',
                'ordering': ['display_name'],
            },
        ),
    ]
