# Generated by Django 4.2.28 on 2026-02-22 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_role_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this record was soft-deleted. NULL means active.', null=True)),
                ('membership_number', models.CharField(db_index=True, help_text='Library card / membership number.', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nic_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('membership_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('PUBLIC', 'Public'), ('SENIOR', 'Senior Citizen'), ('CHILD', 'Child')], db_index=True, default='PUBLIC', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('max_borrows', models.PositiveSmallIntegerField(default=5, help_text='Maximum simultaneous borrows allowed.')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal admin notes.')),
                ('user', models.OneToOneField(blank=True, help_text='Linked system user account (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library Member',
                'verbose_name_plural': 'Library Members',
                'db_table': 'identity_members',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['membership_number'], name='idx_member_number'), models.Index(fields=['status', 'membership_type'], name='idx_member_status_type')],
            },
        ),
    ]
