# Generated by Django 6.0.2 on 2026-02-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp_code',
            field=models.CharField(blank=True, default='', help_text='6-digit OTP sent to the user via email.', max_length=6),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp_verified',
            field=models.BooleanField(default=False, help_text='Whether the OTP has been verified.'),
        ),
    ]
